-- SQLite

CREATE TABLE IF NOT EXISTS loanCR_master(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  generatedDate TEXT NOT NULL,
  name TEXT NOT NULL,
  nric TEXT NOT NULL,
  gender TEXT,
  qualification TEXT,
  dob TEXT,
  race TEXT,
  contactStatus TEXT,
  statusDate TEXT,
  riskLevel TEXT,
  avgPayment TEXT,
  employer TEXT,
  job_employer TEXT,
  annual_income TEXT
);

CREATE TABLE IF NOT EXISTS loanCR_detail(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cr_id INTEGER NOT NULL,
  lender TEXT,
  loan_type TEXT,
  loan_amt REAL,
  loanDate TEXT,
  status_date TEXT,
  outstanding REAL,
  amt1 REAL,
  amt2 REAL,
  amt3 REAL,
  amt4 REAL,
  amt5 REAL,
  amt6 REAL,
  amt7 REAL,
  amt8 REAL,
  amt9 REAL,
  amt10 REAL,
  amt11 REAL,
  amt12 REAL,
  status INTEGER
);

CREATE TABLE IF NOT EXISTS loans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fullname TEXT,
  dob TEXT,
  nric TEXT,
  oldNric TEXT,
  gender TEXT,
  nation TEXT,
  religion TEXT,
  citizenship TEXT,
  maritalStatus TEXT,
  phoneHome TEXT,
  phoneMobile TEXT,
  email TEXT,
  agencyHelp TEXT,
  monthlyIncome REAL,
  highEduInstitution TEXT,
  studyLevel TEXT,
  yearsOfStudy TEXT,
  healthStatus TEXT,
  disabledStatus TEXT,
  bankruptcyStatus TEXT,
  disabilities TEXT,
  workStatus TEXT,
  vulnerableGroups TEXT,
  program1 TEXT,
  program2 TEXT,
  permanentAddress TEXT,
  permanentCity TEXT,
  permanentZipCode TEXT,
  permanentState TEXT,
  mailAddress TEXT,
  mailCity TEXT,
  mailZipCode TEXT,
  mailState TEXT,
  guarantee1 TEXT,
  guarantee2 TEXT,
  status INTEGER
);

CREATE TABLE IF NOT EXISTS guarantees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gName TEXT,
  gNric TEXT,
  gBankruptcyStatus TEXT,
  gDebtStatus TEXT,
  gPhone TEXT,
  gPhoneStatus TEXT,
  gPhoneVeriDate TEXT,
  gMail TEXT,
  gMailStatus TEXT,
  gMailVeriDate TEXT,
  gNo INTEGER
);